Lims 4797 test case
modeso-open-source/1lims-automation pull request #296
Opened 2020-07-17 19:32 UTC by modeso-NahlaMakhlouf

2020-08-17 11:41 UTC, modeso-NahlaMakhlouf commented on github/workflows/CI.yml
> +>>>>>>> 4e5068b766e626514d6a492041541f33ad1c3e80
done

2020-08-17 11:41 UTC, modeso-NahlaMakhlouf commented on ui_testing/testcases/basic_tests/test06_orders.py
> +
done

2020-08-17 11:42 UTC, modeso-NahlaMakhlouf commented on ui_testing/testcases/basic_tests/test06_orders.py
> +        """ LIMS-4797- Make sure the user can press on the cancel button to close the pop-up or from the ( x ) sign
done

2020-08-17 11:45 UTC, modeso-NahlaMakhlouf commented on ui_testing/testcases/basic_tests/test06_orders.py
> +        order, payload = self.orders_api.create_new_order(materialTypeId=1)
done

2020-08-17 11:46 UTC, modeso-NahlaMakhlouf commented on ui_testing/testcases/basic_tests/test06_orders.py
> +
done

2020-08-19 11:24 UTC, ghada-37 requested changes

2020-08-19 11:24 UTC, ghada-37 commented on github/workflows/CI.yml
> +>>>>>>> 4e5068b766e626514d6a492041541f33ad1c3e80
you need to remove this lines + line 13

2020-08-25 23:40 UTC, closed without merging