LIMS-7447: Make sure that user can filter by sub & super scripts in the filter drop down list
modeso-open-source/1lims-automation pull request #301
Opened 2020-07-26 14:47 UTC by modeso-NahlaMakhlouf

- filter in test unit field by super script& sub script values and make sure that items in drop down list includes search text 

```
 C:\Users\ADMIN\PycharmProjects\1lims-automation>nosetests` -vs --nologcapture --tc-file=config.ini ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test068_filter_testunit
_by_scripts_1_super_script
C:\Users\ADMIN\AppData\Local\Programs\Python\Python38\lib\site-packages\nose\plugins\manager.py:394: RuntimeWarning: Unable to load plugin noseprogressive = noseprogressive:ProgressivePlu
gin: No module named '_curses'
  warn("Unable to load plugin %s: %s" % (ep, e),
2020-07-26 16:15:49.313 | INFO     | api_testing.apis.base_api:_get_authorized_session:46 - Get authorized api session.
2020-07-26 16:15:49.316 | INFO     | api_testing.apis.base_api:_get_authorized_session:47 - admin:admin
2020-07-26 16:15:49.842 | INFO     | api_testing.apis.base_api:_get_authorized_session:58 - session ID : _wtY1mNPliMmIaxiQTQW7pK1wBvXeP2UP9PJi3FJo6A .....

DevTools listening on ws://127.0.0.1:61006/devtools/browser/251ef322-8a77-41d7-9e63-177fcafce3c6
LIMS-7447- Make sure that user can filter by sub & super scripts in the filter drop down list [with value='super_script'] ...
2020-07-26 16:16:29.971 | INFO     | ui_testing.testcases.base_test:setUp:27 - Test case : test068_filter_testunit_by_scripts_1_super_script
2020-07-26 16:16:37.801 | INFO     | ui_testing.pages.base_pages:wait_until_page_is_loaded:562 - wait until page is loaded
2020-07-26 16:16:37.899 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-07-26 16:16:39.178 | INFO     | api_testing.apis.orders_api:set_configuration:377 - set order configuration
2020-07-26 16:16:48.699 | INFO     | api_testing.apis.base_api:set_configuration:73 - status code: 1
2020-07-26 16:16:48.705 | INFO     | api_testing.apis.test_unit_api:set_configuration:407 - set test unit configuration
2020-07-26 16:17:17.318 | INFO     | api_testing.apis.base_api:set_configuration:73 - status code: 1
2020-07-26 16:17:17.334 | INFO     | api_testing.apis.base_api:wrapper:122 - GET : https://automation.1lims.com/api/testUnits
2020-07-26 16:17:17.848 | INFO     | api_testing.apis.base_api:wrapper:129 - Status code: 1
2020-07-26 16:17:23.561 | INFO     | ui_testing.pages.base_pages:wait_until_page_is_loaded:562 - wait until page is loaded
2020-07-26 16:17:23.659 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-07-26 16:17:25.168 | DEBUG    | ui_testing.pages.base_pages:sleep_small:43 - wait up to 1 sec
2020-07-26 16:17:28.921 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-07-26 16:17:48.434 | INFO     | ui_testing.testcases.base_test:tearDown:33 - TearDown.     
ok

----------------------------------------------------------------------
Ran 1 test in 120.456s

OK
```

2020-08-17 12:15 UTC, modeso-NahlaMakhlouf commented on .github/workflows/CI.yml
> +          TEST_FILE: ui_testing/testcases/basic_tests/test06_orders.py
done

2020-08-17 12:16 UTC, modeso-NahlaMakhlouf commented on requirements.txt
> +nose-testconfig~=0.10
done

2020-08-17 12:18 UTC, modeso-NahlaMakhlouf commented on ui_testing/testcases/basic_tests/test06_orders.py
> +    def test066_close_testplan_popup(self,button):
done

2020-08-17 12:47 UTC, modeso-NahlaMakhlouf commented on ui_testing/testcases/basic_tests/test06_orders.py
> +        self.test_unit_api.set_configuration()
done

2020-08-19 11:42 UTC, ghada-37 requested changes

2020-08-19 11:42 UTC, ghada-37 commented on ui_testing/testcases/basic_tests/test06_orders.py
> +            self.assertEqual(api['status'], 1)
you can move this command outside if else as it's common between if and else

2020-08-19 11:42 UTC, ghada-37 commented on ui_testing/testcases/basic_tests/test06_orders.py
> +        self.orders_page.get_orders_page()
why you need to navigate to order page, while set up gets order page and you didn't navigated to another page in previous steps

2020-08-19 11:42 UTC, ghada-37 commented on ui_testing/testcases/basic_tests/test06_orders.py
> +        self.base_selenium.scroll(False)
why do you need to scroll her, when orders page is opened, it's already scrolled up

2020-08-19 11:42 UTC, ghada-37 commented on ui_testing/testcases/basic_tests/test06_orders.py
> +
please remove unneeded empty lines

2020-08-19 11:42 UTC, ghada-37 commented on ui_testing/testcases/basic_tests/test06_orders.py
> +        self.assertIsNotNone(self.base_selenium.is_text_included_in_drop_down_items(element='orders:test_units_filter', item_text=unit))
in Jira ticket of this test case, step 5:
you need to assert that result display.
So you will create order with this test unit then get filter result data and assert that unit found in it

2020-08-26 13:12 UTC, closed without merging