LIMS-6632: Orders: Contact configuration approach: In case the user configures the contact field to display name & number this action should reflect on the order active table
modeso-open-source/1lims-automation pull request #416
Opened 2020-09-16 10:30 UTC by omnia353

```
C:\Users\omnia\Documents\1limsNewMaster\1lims-automation>nosetests -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test006_orders.py -m test094 --tc-file=config.ini
c:\users\omnia\lib\site-packages\nose\plugins\manager.py:394: RuntimeWarning: Unable to load plugin noseprogressive = noseprogressive:ProgressivePlugin: No module named 'fcntl'
  warn("Unable to load plugin %s: %s" % (ep, e),
2020-09-16 12:19:56.732 | INFO     | api_testing.apis.base_api:_get_authorized_session:46 - Get authorized api session.
2020-09-16 12:19:56.737 | INFO     | api_testing.apis.base_api:_get_authorized_session:47 - admin:admin
2020-09-16 12:19:57.782 | INFO     | api_testing.apis.base_api:_get_authorized_session:58 - session ID : WEMx9il-XjuLzKvHDm8it_SqSiyzUYssL5501_lFJAQ .....

DevTools listening on ws://127.0.0.1:52981/devtools/browser/36e11f4d-815f-4707-9e2b-30c1dcda8881
test094_change_contact_config_0_Name (ui_testing.testcases.basic_tests.test006_orders.OrdersTestCases) ...
2020-09-16 12:21:10.496 | INFO     | ui_testing.testcases.base_test:setUp:27 - Test case : test094_change_contact_config_0_Name
2020-09-16 12:21:21.346 | INFO     | ui_testing.pages.base_pages:wait_until_page_is_loaded:582 - wait until page is loaded
2020-09-16 12:21:21.440 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:21:22.592 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:21:23.759 | INFO     | api_testing.apis.test_unit_api:set_name_configuration_name_only:427 - set test unit configuration
2020-09-16 12:21:24.804 | INFO     | api_testing.apis.base_api:set_configuration:73 - status code: 1
2020-09-16 12:21:24.812 | INFO     | api_testing.apis.orders_api:set_configuration:432 - set order configuration
2020-09-16 12:21:25.839 | INFO     | api_testing.apis.base_api:set_configuration:73 - status code: 1
2020-09-16 12:21:25.861 | INFO     | ui_testing.testcases.basic_tests.test006_orders:test094_change_contact_config:3246 - get random contact
2020-09-16 12:21:25.872 | INFO     | api_testing.apis.base_api:wrapper:130 - GET : https://automation.1lims.com/api/contacts
2020-09-16 12:21:27.004 | DEBUG    | api_testing.apis.base_api:wrapper:137 - status code: 1
2020-09-16 12:21:27.012 | INFO     | ui_testing.pages.orders_page:open_order_config:345 - open testunits configurations
2020-09-16 12:21:28.163 | INFO     | ui_testing.testcases.basic_tests.test006_orders:test094_change_contact_config:3251 - change contact view by options
2020-09-16 12:21:28.167 | INFO     | ui_testing.pages.contacts_page:open_contact_configurations_options:137 - open contact configurations options
2020-09-16 12:21:28.185 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:21:30.206 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:21:32.037 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
['Name']
2020-09-16 12:21:33.118 | INFO     | ui_testing.pages.contacts_page:clear_all_selected_view_and_search_options:145 - clear selected view and search options of contact name
2020-09-16 12:21:33.333 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:21:42.760 | DEBUG    | ui_testing.pages.base_pages:sleep_small:43 - wait up to 1 sec
2020-09-16 12:21:45.233 | DEBUG    | ui_testing.pages.base_pages:sleep_small:43 - wait up to 1 sec
2020-09-16 12:21:48.043 | INFO     | ui_testing.testcases.basic_tests.test006_orders:test094_change_contact_config:3267 - go to order active table
2020-09-16 12:21:51.347 | INFO     | ui_testing.pages.base_pages:wait_until_page_is_loaded:582 - wait until page is loaded
2020-09-16 12:21:52.878 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:21:53.839 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:21:55.291 | INFO     | ui_testing.pages.orders_page:filter_by_contact:163 - Filter by contact : OMNYA
2020-09-16 12:22:04.307 | INFO     | ui_testing.pages.base_pages:wait_until_page_is_loaded:582 - wait until page is loaded
2020-09-16 12:22:05.446 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:22:06.389 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:22:07.600 | INFO     | ui_testing.testcases.base_test:tearDown:33 - go to dashboard page
2020-09-16 12:22:11.072 | INFO     | ui_testing.testcases.base_test:tearDown:35 - TearDown.     
ok
test094_change_contact_config_1_No (ui_testing.testcases.basic_tests.test006_orders.OrdersTestCases) ...
2020-09-16 12:22:11.078 | INFO     | ui_testing.testcases.base_test:setUp:27 - Test case : test094_change_contact_config_1_No
2020-09-16 12:22:14.522 | INFO     | ui_testing.pages.base_pages:wait_until_page_is_loaded:582 - wait until page is loaded
2020-09-16 12:22:14.580 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:22:15.832 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:22:17.146 | INFO     | api_testing.apis.test_unit_api:set_name_configuration_name_only:427 - set test unit configuration
2020-09-16 12:22:18.958 | INFO     | api_testing.apis.base_api:set_configuration:73 - status code: 1
2020-09-16 12:22:18.967 | INFO     | api_testing.apis.orders_api:set_configuration:432 - set order configuration
2020-09-16 12:22:21.008 | INFO     | api_testing.apis.base_api:set_configuration:73 - status code: 1
2020-09-16 12:22:21.015 | INFO     | ui_testing.testcases.basic_tests.test006_orders:test094_change_contact_config:3246 - get random contact
2020-09-16 12:22:21.023 | INFO     | api_testing.apis.base_api:wrapper:130 - GET : https://automation.1lims.com/api/contacts
2020-09-16 12:22:21.417 | DEBUG    | api_testing.apis.base_api:wrapper:137 - status code: 1
2020-09-16 12:22:21.425 | INFO     | ui_testing.pages.orders_page:open_order_config:345 - open testunits configurations
2020-09-16 12:22:22.463 | INFO     | ui_testing.testcases.basic_tests.test006_orders:test094_change_contact_config:3251 - change contact view by options
2020-09-16 12:22:22.467 | INFO     | ui_testing.pages.contacts_page:open_contact_configurations_options:137 - open contact configurations options
2020-09-16 12:22:22.470 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:22:24.665 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:22:26.631 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
['No']
2020-09-16 12:22:27.623 | INFO     | ui_testing.pages.contacts_page:clear_all_selected_view_and_search_options:145 - clear selected view and search options of contact name
2020-09-16 12:22:27.703 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:22:35.889 | DEBUG    | ui_testing.pages.base_pages:sleep_small:43 - wait up to 1 sec
2020-09-16 12:22:37.489 | DEBUG    | ui_testing.pages.base_pages:sleep_small:43 - wait up to 1 sec
2020-09-16 12:22:39.935 | INFO     | ui_testing.testcases.basic_tests.test006_orders:test094_change_contact_config:3267 - go to order active table
2020-09-16 12:22:42.933 | INFO     | ui_testing.pages.base_pages:wait_until_page_is_loaded:582 - wait until page is loaded
2020-09-16 12:22:42.953 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:22:43.741 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:22:44.730 | INFO     | ui_testing.pages.orders_page:filter_by_contact:163 - Filter by contact : 1366
2020-09-16 12:22:54.990 | INFO     | ui_testing.pages.base_pages:wait_until_page_is_loaded:582 - wait until page is loaded
2020-09-16 12:22:55.312 | DEBUG    | ui_testing.pages.base_pages:sleep_tiny:39 - wait up to 0.5 sec
2020-09-16 12:22:56.082 | DEBUG    | ui_testing.pages.base_pages:sleep_ti [...]

2020-09-17 10:55 UTC, ghada-37 requested changes

2020-09-17 10:55 UTC, ghada-37 commented on ui_testing/elements.py
> +        'configurations': {'method': 'link_text',
it's already defined in general so no need to re-define it
https://github.com/modeso-open-source/1lims-automation/blob/ba7e0d580646ba7cceec19fc3da33c00f1fd1b0f/ui_testing/elements.py#L111

2020-09-17 10:55 UTC, ghada-37 commented on ui_testing/testcases/basic_tests/test006_orders.py
> +        rows = self.orders_page.result_table()
here you need to make sure that value assigned to cell contact exactly equal (name, no, name+no) 
so you need to use :
https://github.com/modeso-open-source/1lims-automation/blob/4b510411856316f9b3e5ae4715a4d2a9a1d7558a/ui_testing/pages/base_selenium.py#L671

2020-09-21 12:55 UTC, 0xIslamTaha requested changes

2020-09-21 12:55 UTC, 0xIslamTaha commented on ui_testing/pages/contacts_page.py
> +        self.sleep_tiny()
remove it

2020-09-21 12:55 UTC, 0xIslamTaha commented on ui_testing/pages/contacts_page.py
> +        print(view_search_options)
replace print with `info`

2020-09-21 13:59 UTC, 0xIslamTaha approved these changes

2020-09-21 14:01 UTC, merged